/* artesian-embed.js -- fit compiled artesian demos into the page.
 *
 * Generated by artesian. Do not edit this file; edit artesian/embed.py.
 *
 * Manages every <iframe data-artesian> on the page: sizes it to its content,
 * and above the app's design width scales the whole app rather than stretching
 * it. The design width is read from the compiled app itself (a
 * <meta name="artesian-design-width">), so the page never repeats it; a
 * data-design-width attribute on the iframe overrides, and with neither the
 * frame is fitted but never scaled.
 */
(function () {
  'use strict';

  // When to re-measure after a frame loads, in milliseconds. Not a poll: the
  // ResizeObserver does the work, and these only catch an update it dropped.
  var RETRIES = [250, 1000, 3000, 10000, 30000];

  function document_of(frame) {
    try {
      return frame.contentDocument || frame.contentWindow.document;
    } catch (e) {
      return null;                 // different origin: leave everything alone
    }
  }

  function design_width(frame) {
    // THE ATTRIBUTE FIRST, and that ordering is the whole point. Reading the
    // width out of the compiled page keeps the number in one place, which is
    // tidy, but it requires the frame's document to be readable at the moment
    // the page lays itself out -- and it is not. An iframe starts on a blank
    // document; on WebKit, which is every browser on an iPad, that is what a
    // page script sees. No meta tag, no design width, and a demo that is never
    // scaled: it sits at its own layout width inside a wider frame with blank
    // space around it.
    //
    // This is not hypothetical. Both GeomorphOnline exercises worked on an
    // iPad while each page hardcoded its own design width, and broke in the
    // commit that replaced that with reading the meta tag.
    var attr = parseFloat(frame.getAttribute('data-design-width'));
    if (attr > 0) { return attr; }
    var doc = document_of(frame);
    if (doc) {
      var meta = doc.querySelector('meta[name="artesian-design-width"]');
      if (meta) {
        var declared = parseFloat(meta.getAttribute('content'));
        if (declared > 0) { return declared; }
      }
    }
    return 0;                      // 0 : fit, but never scale
  }

  function available_width(frame) {
    // Measure the PARENT, never the frame. Once the frame is zoomed, its own
    // clientWidth is reported in its local coordinates -- it would read back
    // the design width, give a factor of 1, and oscillate. The parent is not
    // zoomed, so its width is the honest one.
    var host = frame.parentElement;
    if (!host || !host.clientWidth) {
      return frame.getBoundingClientRect().width;
    }
    // clientWidth INCLUDES the parent's padding, and the frame lives in the
    // content box. Scaling to the padded width overflows the column by
    // exactly the padding -- invisible in a container that has none, which is
    // why this survived two deployments and only showed up on a test page
    // with 16 px of it.
    var style = window.getComputedStyle(host);
    var pad = (parseFloat(style.paddingLeft) || 0)
            + (parseFloat(style.paddingRight) || 0);
    return Math.max(host.clientWidth - pad, 0);
  }

  function manage(frame) {
    var adjusting = false;
    var observer = null;
    var observed = null;           // the document the observer is attached to

    function attach() {
      // An iframe does not start empty: it starts with a BLANK document, whose
      // readyState is already 'complete'. Observing that one attaches to a body
      // that is about to be thrown away and will never resize again, and
      // reading the design width from it finds no meta tag -- so the demo is
      // never scaled and the height is whatever the blank document had. That
      // is what an iPad showed, and no desktop engine did, because there the
      // real document arrives before the script looks.
      //
      // So the observer follows the CURRENT document, and re-attaches whenever
      // it changes.
      if (typeof ResizeObserver === 'undefined') { return; }
      var doc = document_of(frame);
      if (!doc || !doc.body || doc === observed) { return; }
      if (observer) { observer.disconnect(); }
      observer = new ResizeObserver(fit);
      observer.observe(doc.body);
      observed = doc;
    }

    function fit() {
      attach();                    // the document may have been replaced
      if (adjusting) { return; }   // ignore the events our own writes cause
      var doc = document_of(frame);
      if (!doc || !doc.body) { return; }

      adjusting = true;

      var design = design_width(frame);
      var available = available_width(frame);
      // Below the design width, stay at 1 and let the app lay itself out
      // responsively -- a phone should reflow, not render a shrunken page.
      var factor = (design && available > design) ? available / design : 1;

      if (factor === 1) {
        frame.style.zoom = '';
        // NOT width: 100%. WebKit -- which is every browser on an iPad --
        // sizes an iframe to its content rather than honouring a percentage,
        // and a stretch-to-fit app then grows with it off the side of the
        // page. min-width is honoured where width: 100% is not.
        frame.style.width = '1px';
        frame.style.minWidth = '100%';
      } else {
        // Zoom the frame itself, not its contents. `zoom` scales layout as
        // well as paint, so the frame's interior measures the design width
        // across and the plot re-renders at full resolution rather than being
        // upscaled and blurred.
        frame.style.zoom = factor;
        // An explicit pixel width in the frame's own coordinates: a percentage
        // would resolve against the parent and then be scaled by the zoom,
        // overflowing the page.
        frame.style.width = design + 'px';
        frame.style.minWidth = '0';       // or the min-width above wins
      }

      var previous = frame.style.height;
      // Collapse before measuring: Panel's layout fills whatever height it is
      // given, so measuring a tall frame reports back the height we last set.
      // Adding padding to the measurement makes it grow on every callback.
      frame.style.height = '0px';
      var height = Math.max(doc.body.scrollHeight,
                            doc.documentElement.scrollHeight);
      frame.style.height = height > 0 ? Math.ceil(height) + 'px'
                                      : (previous || '600px');

      if (typeof requestAnimationFrame === 'function') {
        requestAnimationFrame(function () { adjusting = false; });
      } else {
        setTimeout(function () { adjusting = false; }, 0);
      }
    }

    function watch() {
      // Panel renders asynchronously, and the first render waits on Pyodide
      // downloading -- tens of seconds. Watch the body rather than measure
      // once; fit() attaches to whichever document is current.
      fit();
      // And re-measure a few times anyway. `adjusting` suppresses the observer
      // callbacks our own writes cause, but it cannot tell those from a real
      // one arriving in the same moment, so a render that lands inside that
      // window is dropped and the frame keeps whatever height it had when the
      // app was still laying itself out -- blank space under the demo, on a
      // machine fast enough to hit it. A few later measurements cost nothing
      // and make that self-correcting rather than permanent.
      for (var i = 0; i < RETRIES.length; i++) {
        setTimeout(fit, RETRIES[i]);
      }
    }

    frame.style.border = frame.style.border || 'none';
    frame.style.display = 'block';
    // The frame is sized to its content, so it has nothing to scroll -- and if
    // it can scroll, a touch drag pans the demo off the edge of its own frame
    // and there is no obvious way to get it back. Reported on an iPad, where a
    // rounding difference of a pixel or two is enough to make the inner
    // document scrollable. Set in the page's HTML as well, since some engines
    // only honour it before the frame loads.
    frame.setAttribute('scrolling', 'no');
    frame.addEventListener('load', watch);
    window.addEventListener('resize', fit);
    var doc = document_of(frame);
    if (doc && doc.readyState === 'complete') {
      watch();                     // already loaded from cache
    }
  }

  function start() {
    var frames = document.querySelectorAll('iframe[data-artesian]');
    for (var i = 0; i < frames.length; i++) { manage(frames[i]); }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start);
  } else {
    start();
  }
})();
